[msg MSG_000_3_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ざわつく声)[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 1 65535 0]Certo, essa foi uma apresentação esplêndida[n]do clube de dança![n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]Pessoal, vamos dar outra[n]grande salva de palmas![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Seus esforços foram ignorados...[n]ainda assim eles continuam a dar[n]tudo de si.[n][f 1 3 65535][w][e]
[s][bup 0 109 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 0 0 4 65535 0]Essa é a juventude de hoje, eu acho.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Você tem razão.[e]
[s]São todos esforços inúteis.[e]
[s]Você é realmente nobre.[e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 1 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Isso inclui você, já que é jovem ainda.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Talvez... Mas aqueles que trabalham duro[n]serão apreciados um dia.[n][f 1 3 65535][w][e]
[s][bup 0 109 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 0 0 7 65535 0]Ei, eu não tô meio que falando feito um[n]bom professor?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]O quê!?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]...Enfim, sobre o que o Akechi-kun disse[n]mais cedo...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 10 65535 0]E agora, é hora da sua[n]tradição de Shujin favorita:[n]o Evento Especial de Partilha![n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 65535 0]Muitos aplausos, pessoal![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]...Quer ir pra algum lugar onde[n]possamos ficar sozinhos?[n]Tem algo que eu quero falar com você.[n][f 1 3 65535][w][e]
[s][bup 0 109 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 0 0 13 65535 0]Aproveita o pós-festival. Mas passa na[n]associação estudantil assim que terminar.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 14 65535 0]Beleza, quem aqui tem algo a dizer?[n]Alguém, ninguém!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 16 65535 0]Não? Então terei que escolher alguém![n][f 1 3 65535][w][e]
[s][vp 8 0 0 17 65535 0]Que tal...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 18 65535 0]Aquele bom senhor ali![n][f 1 3 65535][w][e]

[msg MND_015_0_0]
[s][vp 8 0 0 0 65535 0]Infelizmente, sou eu...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 19 65535 0]Vamos, suba aqui![n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Não, valeu.[e]
[s]Estou com dor de cabeça.[e]

[msg MSG_018_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 20 65535 0]Olha, olha! Você não é tímido, não é?![n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 65535 0]Ou ele é um espírito livre que sempre faz[n]o que quer ou um avoado que tá alheio[n]à situação![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](笑い)[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Eu deveria ir ver a Kawakami...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Presentatore dello spettacolo]]
[s][vp 8 0 0 22 65535 0]Bem, agora que a audiência está[n]aquecendo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 23 65535 0]Vamos para o próximo participante![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

