[msg MND_000_5_0]
[s][vp 1 0 0 0 0 0]Saí da festa com a Kasumi[n]para me refrescar lá fora...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Foi cansativo, mas que demais![n]Sinto que dançei até[n]dizer chega lá.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Percebi.[e]
[s]Ótimo, do jeito que pensei.[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ah, obrigada![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Obrigada.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Studente sbalordito]]
[s][f 4 10 65535 0 0][vp 8 0 0 4 5 0]Uau! Aquela dança foi incrível...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Studentessa sbalordita]]
[s][f 4 10 65535 0 0][vp 8 0 0 5 9 0]Não é? Fiquei de cara.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 6 65535 0][vp 1 0 0 6 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]É meu pai. Ele quer que eu volte para casa[n]antes que fique tarde demais.[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Desculpa por te deixar assim,[n]mas eu realmente tenho que ir.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Toma cuidado no caminho pra casa.[e]
[s]Quer que eu te acompanhe?[e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Pode deixar! Com licença.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Obrigada. Mas ficarei bem.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]A festa pós-festival foi[n]sensacional! Especialmente com você![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Até breve![n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 1 0 0 0 0 0]O ginásio se aquietou...[n]Parece que o baile acabou...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Eu deveria ir para casa...[n][f 1 3 65535][w][e]

